import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'ROS 2 Nervous System',
      items: [
        'docs/ros2-nervous-system/fundamentals',
        'docs/ros2-nervous-system/python-agents',
        'docs/ros2-nervous-system/urdf-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Digital Twin (Gazebo & Unity)',
      items: [
        'docs/digital-twin/physics-simulation',
        'docs/digital-twin/unity-environments',
        'docs/digital-twin/sensor-simulation',
      ],
    },
    {
      type: 'category',
      label: 'AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'docs/ai-robot-brain/nvidia-isaac-sim',
        'docs/ai-robot-brain/isaac-ros-perception',
        'docs/ai-robot-brain/navigation-nav2',
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA) Integration',
      items: [
        'docs/vla-integration/voice-to-action',
        'docs/vla-integration/language-planning',
        'docs/vla-integration/capstone-humanoid',
      ],
    },
    {type: 'autogenerated', dirName: '.'},
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
